source "https://rubygems.org"
ruby "2.0.0"
gem 'sinatra', '1.3.4'
gem 'data_mapper'
gem 'pg', '0.17.1'
gem 'dm-postgres-adapter'
gem 'shotgun'
gem 'bcrypt-ruby',			require: 'bcrypt'
gem 'rack-flash3', '1.0.1', require: 'rack/flash'
gem 'warden', '1.2.1'



