
development:
  adapter: postgresql
  host: localhost
  database: rails_tut_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  host: localhost
  database: rails_tut_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: rails_tut_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test